parameters:
#    sm_api.example.class: SM\Bundle\ApiBundle\Example

services:
#    sm_api.example:
#        class: %sm_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
